version: "0.2"
ignorePaths: 
  - pnpm-lock.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - ˈdʒɑːvəˌskrɪpt
  - esbuild
  - Polyrepo
  - reactjs
  - speicification
  - Turborepo
ignoreWords: []
import: []
